---
- name: centos install httpd
  hosts: all
  become: yes

  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present

    - name: started httpd
      service:
        name: httpd
        state: started
        enabled: true
