---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-jen
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: jen-pods-label
  template: 
    metadata:
      name: jen-pod
      labels :
        app: jen-pods-label
    spec:
      containers: 
      - name: jenkins
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: jen-lb
spec: 
  ports:
  - name: jen-port
    targetPort: 80
    port: 80
  selector: 
    app: jen-pods-label
  type: LoadBalancer
